FROM python:3.10
WORKDIR /app

RUN pip install "poetry==1.7.1"
COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

COPY src src
ENV PYTHONPATH "${PYTHONPATH}:/app"
CMD ["python", "src/main.py", "bot"]
