name: Pull request checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.2.0

      - name: Install dependencies
        run: poetry install

      - name: Check code formatting
        run: make format-check

      - name: Run mypy
        run: make mypy

#      - name: Run tests
#        run: make test
